openapi: 3.0.3
info:
  title: KinkinaSaifu API
  version: 1.1.0
  description: STD22079 - STD22028
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: Accounts
    description: Account related endpoint
  - name: Transactions
    description: Transaction related endpoint
paths:
  /account:
    get:
      tags:
        - Accounts
      summary: Returns a list of all accounts
      operationId: getAllAccount
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
    put:
      tags:
        - Accounts
      summary: Create or update an (list of) account
      operationId: crupdateAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '201':
          description: Account created
  /account/{id}:
    get:
      tags:
        - Accounts
      summary: Returns an account by id
      operationId: getAccountById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: An account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
  /transaction:
    get:
      tags:
        - Transactions
      summary: Returns a list of all transactions
      operationId: getAllTransactions
      responses:
        '200':
          description: A list of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
    put:
      tags:
        - Transactions
      summary: Create or update a (list of) transaction
      operationId: crupdateTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          description: Transaction created
  /transaction/{id}:
    get:
      tags:
        - Transactions
      summary: Returns a transaction by id
      operationId: getTransactionById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
    delete:
      tags:
        - Transactions
      summary: Deletes a transaction by id
      operationId: deleteTransactionById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Transaction deleted
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
        principalCurrency:
          $ref: '#/components/schemas/Currency'
        name:
          type: string
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        type:
          type: string
          enum: [Bank, Cash, Mobile Money]
    Transaction:
      type: object
      properties:
        id:
          type: string
        label:
          type: string
        amount:
          type: number
        dateTime:
          type: string
          format: date-time
        transactionType:
          type: string
          enum: [debit, credit]
    Currency:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        code:
          allOf:
            - $ref: '#/components/schemas/CurrencyCode'
    CurrencyCode:
      type: string
      enum:
        - USD
        - EUR
        - JPY
        - GBP
        - CAD
        - MGA
